name: liaison_tutorial
channels:
  - defaults
  - conda-forge
dependencies:
  - pip=23.2.1
  - python=3.10
  - premise=1.8.1
  - pip:
    - attrs==23.1.0
    - bottleneck==1.3.7
    - brightway2==2.4.3
    - bw-migrations==0.2
    - bw2analyzer==0.10
    - bw2calc==1.8.2
    - bw2data==3.6.6
    - bw2io==0.8.7
    - bw2parameters==1.1.0
    - cached-property==1.5.2
    - certifi==2023.7.22
    - cffi==1.15.1
    - chardet==5.2.0
    - charset-normalizer==3.2.0
    - contourpy==1.1.0
    - cryptography==41.0.3
    - cycler==0.11.0
    - fonttools==4.42.1
    - idna==3.4
    - importlib-resources==6.0.1
    - jinja2==3.1.2
    - jsonschema==4.19.0
    - jsonschema-specifications==2023.7.1
    - kiwisolver==1.4.5
    - markupsafe==2.1.3
    - matplotlib==3.7.2
    - numpy==1.23.5
    - openpyxl==3.1.2
    - packaging==23.1
    - pandas==1.5.3
    - pillow==10.0.0
    - premise-gwp==0.9.6
    - pycparser==2.21
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2023.3
    - pyyaml
    - referencing==0.30.2
    - requests==2.31.0
    - rpds-py==0.9.2
    - scipy==1.11.2
    - six==1.16.0
    - tqdm==4.66.1
    - urllib3==1.26.16
    - wcwidth==0.2.6
    - wurst==0.3.5
    - xarray==2023.8.0
    - zipp==3.16.2

